name: BrakeliteRelease

on:
    release:
        types: [created]
    workflow_dispatch:

jobs:
    create-release-binaries:
        runs-on: ubuntu-latest
        steps:
            -
                name: Run Apt-Get Deps
                run: sudo apt-get install gcc libgtk-3-dev libappindicator3-dev
            -
                name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -
                name: Set up Go
                uses: actions/setup-go@v2
                with:
                    go-version: 1.16
            -
                name: Create Linux/AMD64 Binary
                run: env GOOS=linux GOARCH=amd64 go build -o build/linux/amd64/brakelite
            -
                name: Archive Artifacts
                uses: actions/upload-artifact@v2
                with:
                    name: brakelite-linux-amd64
                    path: build/linux/amd64/brakelite
