# This is a basic workflow to help you get started with Actions

name: BrakeliteRelease

on:
    release:
        types: [created]
    workflow_dispatch:

jobs:
    release-linux-amd64:
        name: release linux/amd64
        runs-on: ubuntu-latest
        steps:
        - run: sudo apt-get install gcc libgtk-3-dev libappindicator3-dev
        - uses: actions/checkout@v2
        - uses: wangyoucao577/go-release-action@v1.18
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            goos: linux
            goarch: amd64
